import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppFooter from "./components/AppFooter";
import AppHeader from "./components/AppHeader";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event App - Next.js + Tailwind CSS + TypeScript",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <main className="flex items-center justify-between p-24">
          {children}
        </main>
        <AppFooter />
      </body>
    </html>
  );
}
