import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppFooter from "./components/AppFooter";
import AppHeader from "./components/AppHeader";
import App from "./components/App";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Event App - Next.js + Tailwind CSS + TypeScript",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App>
          <AppHeader />
          <main className="p-4">{children}</main>
          <AppFooter />
        </App>
      </body>
    </html>
  );
}
